language: ruby
rvm:
  - 2.3.1

env:
  SECRET_KEY_BASE="$(bundle exec rake secret)"

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - bundle exec rake db:schema:load

