# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
ADMIN_NAME: First User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: please
ROLES: [admin, coordinator, recruiter, user]

MAILER_INTERCEPTOR: kwalters@taphere.com
MAILER_USERNAME: jams@cattywamp.us
MAILER_PASSWORD: p@ssw0rd
MAILER_SMTP_ADDRESS: mail.cattywamp.us

GOOGLE_CLIENT_ID:
GOOGLE_CLIENT_SECRET:

NEWRELIC_LICENSE_KEY:

