require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JudgesController do
  login :admin
  
  # This should return the minimal set of attributes required to create a valid
  # Judge. As you add validations to Judge, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    person = FactoryGirl.create(:person)
    event = FactoryGirl.create(:event)
    FactoryGirl.attributes_for(:judge).merge({person_id: person.id, event_id: event.id})
  end

  def invalid_attributes
    FactoryGirl.attributes_for(:judge) # missing person/event associations
  end

  describe "GET index" do
    it "assigns all judges as @judges" do
      judge = Judge.create! valid_attributes
      get :index, {}
      assigns(:judges).should eq([judge])
    end
  end

  describe "GET show" do
    it "assigns the requested judge as @judge" do
      judge = Judge.create! valid_attributes
      get :show, {:id => judge.to_param}
      assigns(:judge).should eq(judge)
    end
  end

  describe "GET new" do
    it "assigns a new judge as @judge" do
      get :new, {}
      assigns(:judge).should be_a_new(Judge)
    end
  end

  describe "GET edit" do
    it "assigns the requested judge as @judge" do
      judge = Judge.create! valid_attributes
      get :edit, {:id => judge.to_param}
      assigns(:judge).should eq(judge)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Judge" do
        expect {
          post :create, {:judge => valid_attributes}
        }.to change(Judge, :count).by(1)
      end

      it "assigns a newly created judge as @judge" do
        post :create, {:judge => valid_attributes}
        assigns(:judge).should be_a(Judge)
        assigns(:judge).should be_persisted
      end

      it "redirects to the created judge" do
        post :create, {:judge => valid_attributes}
        response.should redirect_to(Judge.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved judge as @judge" do
        # Trigger the behavior that occurs when invalid params are submitted
        Judge.any_instance.stub(:save).and_return(false)
        post :create, {:judge => invalid_attributes}
        assigns(:judge).should be_a_new(Judge)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Judge.any_instance.stub(:save).and_return(false)
        post :create, {:judge => invalid_attributes}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested judge" do
        judge = Judge.create! valid_attributes
        # Assuming there are no other judges in the database, this
        # specifies that the Judge created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Judge.any_instance.should_receive(:update_attributes).with({ "person" => "" })
        put :update, {:id => judge.to_param, :judge => { "person" => "" }}
      end

      it "assigns the requested judge as @judge" do
        judge = Judge.create! valid_attributes
        put :update, {:id => judge.to_param, :judge => valid_attributes}
        assigns(:judge).should eq(judge)
      end

      it "redirects to the judge" do
        judge = Judge.create! valid_attributes
        put :update, {:id => judge.to_param, :judge => valid_attributes}
        response.should redirect_to([judge.event, judge])
      end
    end

    describe "with invalid params" do
      it "assigns the judge as @judge" do
        judge = Judge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Judge.any_instance.stub(:save).and_return(false)
        put :update, {:id => judge.to_param, :judge => invalid_attributes}
        assigns(:judge).should eq(judge)
      end

      it "re-renders the 'edit' template" do
        judge = Judge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Judge.any_instance.stub(:save).and_return(false)
        put :update, {:id => judge.to_param, :judge => invalid_attributes}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested judge" do
      judge = Judge.create! valid_attributes
      expect {
        delete :destroy, {:id => judge.to_param}
      }.to change(Judge, :count).by(-1)
    end

    it "redirects to the previous page" do
      judge = Judge.create! valid_attributes
      delete :destroy, {:id => judge.to_param}
      response.should redirect_to(event_judges_path(judge.event))
    end
  end

end
